### ISSUE TITLE
Deploy to templating engine to production

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/templating-engine#108]

**Comment by libdgg** [comment]
Emailed Steve Collins to request that we’d like to have Middleware set up site `engine/staging` as a symlink for `engine/production` on the web server. This will ensure that staging and production will use the same engine whenever we deploy to production.

**Comment by kristianserrano** [comment]
I've deployed master to production and published the content on that same server. I need to upload the website root assets so that I can run the indexer and so that it'll handle the incoming requests properly.

@libdgg we seem to be having permission issues with the website root folder `libraries.emory.edu`. I am unable to upload files to that directory. Can you ping Steve or James about to see if they can verify the permissions on that folder?

**Comment by libdgg** [comment]
I slacked James and Steve about the permissions question above.

**Comment by kristianserrano** [comment]
@libdgg the issue has been resolved.

**Comment by kristianserrano** [comment]
https://preview.libraries.emory.edu is working and the index seems to be updating appropriately. Staging is also still functioning properly as well. Please, everyone, kick the tires.

**Comment by laurenhamel** [comment]
@kristianserrano, it looks like some of the template-level data is missing in addition to the select a library stuff. I'm going to republish it from Cascade, then reindex.

**Comment by laurenhamel** [comment]
@kristianserrano, I'm trying to reindex `prod` but nothing is happening. After taking a look at the root assets in `libraries.emory.edu/`, it looks like the website root assets may have been copied over from `staging` (e.g., environment still says `staging`). Was this intentional for preview testing? If not, I think we need to redeploy the correct website root assets for `prod`, then make sure everything is working again as expected.

**Comment by kristianserrano** [comment]
No it wasn't intentional. I thought they used the same files, and that prod had never been updated since it wasn't actively being used. Apologies for that.

**Comment by laurenhamel** [comment]
No worries. I'm going to redeploy the website root assets and go from there with testing.

**Comment by kristianserrano** [comment]
This is complete.
