### ISSUE TITLE
Image URLs in CSS resolving to absolute paths at libraries.emory.edu

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/templating-engine#111]
... instead of `preview.libraries.emory.edu`. Perhaps these should be relative or root relative URLs even.

**Comment by laurenhamel** [comment]
@kristianserrano, I'm dropping a comment here to help clarify why the paths are absolute: Originally, these were root relative URLs, but when troubleshooting the hero images not appearing on Exhibition pages, I discovered that to root relative and relative URLs were the culprit for the images not loading. I can't remember exactly why that was, but I vaguely remember it had something to do with how the `background-image` CSS property and/or CSS variables were unable to resolve relative and root relative paths.
