### ISSUE TITLE
Improve the templating engine's page rendering time

### ISSUE THREAD

**Issue by laurenhamel** [emory-libraries/templating-engine#27]
Currently, the templating engine is using indexing (based on the data folder's IA) to first identify available routes within the site before verifying if the requested endpoint is valid and attempting to render the page. Because the indexing process has to find and read all files within the file tree, this can be costly to site performance. Two possible solutions that we're considering are:

1. **Cache the index to prevent having to re-index the entire site for each new incoming request.** This caching would be implemented in two parts, where we, first, cache the file tree's structure and metadata about each file (like when it was last modified) and then, second, cache the data for all file's within the file tree. Then, for each incoming request, we could re-index the first part of the file tree in order to determine if the site's IA has changed and only optionally re-index the second part of the index if changes to the site's IA were detected.

2. **Reconfigure the templating engine to automatically assume that all incoming requests are likely pointing to a valid endpoint.** In this approach, we'd use the endpoint of the incoming request to look for a data file at an identical endpoint within the data folder. If a data file is found, then we would read that data file to get it's contents, including its page type, then identify its corresponding template and/or determine if the page redirects. If a data file doesn't exist, then we would return a 404 error page instead.

**Comment by laurenhamel** [comment]
@kristianserrano, here's the issue regarding the caching and slow page loading that we talked about earlier. Also, another thing I just thought about for approach 2 above is that we'll want to figure out how we go about caching that data too. Something to also consider for either approach may be whether or not we should cache the actual endpoint once they're identified.

**Comment by laurenhamel** [comment]
@kristianserrano, I just had another idea. We could also potentially offload the site indexing and transforming/translating of the XML data files into a cron job or similar that gets triggered on publish.

**Comment by kristianserrano** [comment]
I'm not opposed to that. How long would that triggered process take to update the index, or how quickly could someone see the content on the site?

**Comment by laurenhamel** [comment]
I imagine it wouldn't take but mere seconds after a publish. Another thing worth noting here, also, the page load speed also affects loading of assets. While this isn't necessarily an issue for things like images, videos, documents, etc., it does also affect CSS and JS files, making this more of an issue that needs to be addressed sooner rather than later if we especially want to avoid delayed styling.
