### ISSUE TITLE
Implement benchmarking for templating engine

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/templating-engine#28]
For benchmarking, we'll use a [performance analyzer](https://github.com/bvanhoekelen/performance) to identify which parts of the templating engine are taking the longest to execute. Benchmarking will want to do a comparison of page load times via `localhost` (with and without the use of a tunnel, such as `ngrok`) and/or one or more server environments.

To Dos
---
- [x] Benchmark initial templating engine performance
- [ ] Benchmark templating engine performance after Test A (#33)
- [x] Benchmark templating engine performance after Test B (#34)
- [x] Compare all benchmarks and decide on the best optimization approach

**Comment by laurenhamel** [comment]
Benchmarking has been conducted for `localhost`, `ngrok`, and `dev.libraries.emory.edu`, and the [results](https://drive.google.com/open?id=1rF7OUne_ydDXBvJMF2bnjgnB4D6xXc2wOaKBCeZ0EPY) have been compiled into a Google Sheet. In sum, as we originally thought, the indexing process that the templating engine uses is causing a bottleneck in page load time. From here, I'm thinking that it may be best if we proceed to A/B test our proposed solutions: 

1. Offload the indexing into a separate process that gets triggered on publish (`fswatch`)
2. Rearchitect the templating engine to eliminate indexing and use minimal file processing
