### ISSUE TITLE
Set up and test network performance with ngrok

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/templating-engine#29]

**Comment by laurenhamel** [comment]
Based on the [benchmarking results](https://drive.google.com/open?id=1rF7OUne_ydDXBvJMF2bnjgnB4D6xXc2wOaKBCeZ0EPY), I think it's fair to say that networking doesn't seem to be an issue in terms of performance. However, I am still questioning whether or not slow server performance may still be a contributing factor. When testing on `localhost` (both with and without the use of `ngrok`), the benchmarking outcomes for the templating engine's indexing process averaged about 75% faster completion times in comparison to the benchmarking tests that were run for `dev.libraries.emory.edu`.
