### ISSUE TITLE
Test data/routes

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/templating-engine#42]

**Comment by laurenhamel** [comment]
@nikdragovic and @kristianserrano, to me this seems like an older issue that we may have inserted as a placeholder for preliminary templating engine work, and we can maybe close it as `invalid` at this point?

**Comment by laurenhamel** [comment]
My other impression is that this could've been relating to the templating engine work that was captured in #47.

**Comment by kristianserrano** [comment]
Yeah, there's quite a few of these that we need to clean up (or turn into epics?).
