### ISSUE TITLE
Pass query parameters to pages when rendered

### ISSUE THREAD

**Issue by laurenhamel** [emory-libraries/templating-engine#44]
This will mostly be needed for directory pages that offer a filtered or category view.

**Comment by laurenhamel** [comment]
@kristianserrano, this is ready for you to test. I went ahead and opened a PR to help expedite things, since I'll want to factor this in to the final Services Directory page.

**Comment by lovinscari** [comment]
@kristianserrano Is there anything preventing you from testing this issue? If there is can you please comment and move to blocked? Thanks.

**Comment by kristianserrano** [comment]
This is ready for deployment.

**Comment by kristianserrano** [comment]
@laurenhamel Do you want me to go ahead and deploy or do you have other things pending that you want to bundle into the deployment?

**Comment by laurenhamel** [comment]
@kristianserrano, I'm moving this into Sprint 10, and we can deploy this along with the improved error handling (#50 and #60) at the same time.
