### ISSUE TITLE
Support responsive images by autogenerating multiple sizes

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/templating-engine#54]
Consider this a wishlist item for well after launch.

As a financially constrained student using a mobile device to access the website, I would like the page to use an image appropriate for my device's data speed and screen size so that my data plan doesn't become expensive or get throttled.

As a student accessing the website using an iPhone on a service plan paid for by my parents, I would like to see high-density images on my Retina screen, so that photos looks crisp and my eyes don't bleed.

For more information about responsive images...
https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

**Comment by laurenhamel** [comment]
This is no longer relevant as the templating engine is being decommissioned for Phase 2.
