### ISSUE TITLE
Add index update API calls as output type on Cascade Configuration Sets

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/templating-engine#61]

**Comment by kristianserrano** [comment]
@laurenhamel I'm struggling with authentication in my local environment. Not sure if I'm sending the credentials incorrectly with the post or if the engine is doing something incorrectly. Wondering if we really need authentication at all.

In either case, I'd like to deploy to dev for verification, but I want to check with you before I do in case you have something up there you're working with.

**Comment by laurenhamel** [comment]
@kristianserrano, I tested this with the changes I made to the templating engine and did not run into any issues. Feel free to test again while reviewing the PR (#68) I just submitted. Once that gets merged, I think this will be ready to move to "To Accept."

**Comment by laurenhamel** [comment]
@kristianserrano, the `.env` information has been updated for all environments. You'll want to make sure these changes are reflected in the Cascade configurations before testing this again.
