### ISSUE TITLE
Setup Cron Jobs for auto indexing in staging site every hour

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/templating-engine#62]

**Comment by laurenhamel** [comment]
**Status update:** I reached out to middleware to request that a cron job be setup. We're now waiting to hear back from them. I did ask that they try to get this done by EOD today (Friday 6/7) or by early Monday if possible, so stay tuned.

**Comment by laurenhamel** [comment]
Middleware is in the works of getting this setup. A cron job will be added on each server, each running 30 minutes apart.

**Comment by laurenhamel** [comment]
Cron jobs have been setup and should be running. Middleware will reach out if any errors arise. Otherwise, @nikdragovic, this should be ready for acceptance.

**Comment by laurenhamel** [comment]
Adding another note to this: We'll also want to get the same cron job setup on production when the time comes. For now, it's only setup on `staging`. We'll likely want to add another issue for this.

**Comment by laurenhamel** [comment]
I added two issues to the backlog for Sprint 13 and 14 to setup cron jobs on `beta` and `production`.
