### ISSUE TITLE
Fix indexing timeout error

### ISSUE THREAD

**Issue by laurenhamel** [emory-libraries/templating-engine#85]
The indexing process is running into a timeout error due to the prerender callback. As more pages are populated in the site, the prerender script is taking an excessive amount of time to loop through each page and send a `curl` request to force the templating engine to recache the page.

**Comment by laurenhamel** [comment]
@kristianserrano and @nikdragovic , all fixes to closeout this issue should be deployed in `dev` and `qa` environments, and I went ahead an triggered a reindexing for both. I'm moving this to "To Test" in hopes that we can get this moved into "To Accept" by the EOD. If testing looks good on your end, I'll go ahead and deploy to the `staging` environment for closeout.

**Comment by nikdragovic** [comment]
@laurenhamel Awesome, thank you so much. Just so I'm sure, I only need to review once you notify me that the issue has moved to "To Accept"?

**Comment by laurenhamel** [comment]
@nikdragovic, this has been moved to "To Accept." I went ahead and deployed to `staging`, published all content out of Cascade, then forced a reindex.

**Comment by nikdragovic** [comment]
@laurenhamel Thanks so much. I started reviewing template-level issues in QA, adding links to examples in Cascade and in the qa environment. I'll switch to staging now. 

I'm not sure what criteria I should use to close this issue (#85), but if it's resolved to your satisfaction, I will close it as soon as I can finish my functional review from the stakeholder perspective. Thanks again and we can catch up at standup tomorrow.

**Comment by nikdragovic** [comment]
July 11 standup - Nik will do additional testing on templates to close out this issue.

**Comment by laurenhamel** [comment]
@nikdragovic, these changes should be reflected in templating engine. If/when you create a test page for the Index page type and publish it out, please do try out the indexing within Cascade to make sure you're not running into any issues with it.
