### ISSUE TITLE
Some bio page details not displaying in template

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/templating-engine#93]
Cascade entry: https://cascade.emory.edu/entity/open.act?id=1b6f70360ae72098230fc981a5305f72&type=page&confId=28a9e6ab0ae720982da9b0c8e085c1cc

Staging URL: https://staging.libraries.emory.edu/contact/bailey-jody

Example content missing: Education entries

I've tried deleting and rebuilding the index after publishing the page to both QA and staging; neither one diplayed the missing content after.

**Comment by laurenhamel** [comment]
This is no longer relevant as the templating engine is being decommissioned for Phase 2.
